### ISSUE TITLE
Having some trouble with the Visual Studio build... please help?

### ISSUE THREAD

**Issue by atraczyk** [ShiftMediaProject/gnutls#1]
Hello, I'm trying to test the Visual Studio build with the following test code:

``` cxx
extern "C" {
#include <gnutls\gnutls.h>
#include <gnutls\x509.h>
}

#include <iostream>

int main()
{
    gnutls_global_init();
    gnutls_x509_privkey_t key;
    unsigned int key_length = 4096;
    if (gnutls_x509_privkey_init(&key) != GNUTLS_E_SUCCESS)
        std::cout << "Failed to create private key" << std::endl;
    else
        std::cout << key << std::endl;
    int err = gnutls_x509_privkey_generate(key, GNUTLS_PK_RSA, key_length, 0);
    if (err != GNUTLS_E_SUCCESS) {
        gnutls_x509_privkey_deinit(key);
        std::cout << "Can't generate RSA key pair: " << gnutls_strerror(err) << std::endl;
    }
    else {
        std::cout << "Success" << std::endl;
    }
    system("pause");
    return 0;
}
```

and I get a heap corruption exception inside

``` cxx
gnutls_x509_privkey_generate(key, GNUTLS_PK_RSA, key_length, 0);
```

I'm wondering if I am missing something, or you have run into this before. I've traced it down to

``` cxx
 __gmp_default_free(...)
```

 in gmp/memory.c. 

The call stack usually looks like this:

```
    testbox.exe!__gmp_default_free  C
    testbox.exe!__gmp_randclear_mt  C
    testbox.exe!nettle_random_prime C
    testbox.exe!nettle_random_prime C
    testbox.exe!nettle_random_prime C
    testbox.exe!nettle_random_prime C
    testbox.exe!nettle_random_prime C
    testbox.exe!nettle_random_prime C
    testbox.exe!nettle_random_prime C
    testbox.exe!nettle_rsa_generate_keypair C
    testbox.exe!wrap_nettle_pk_generate_keys    C
    testbox.exe!gnutls_x509_privkey_generate    C
    testbox.exe!main    C++
```

recompiling gmp with DEBUG defined makes `__gmp_default_free(...)` try to spit out "gmp: (free) data clobbered after allocation block\n". But it fails most of the time before any data makes it to the console.

Anyways, any help or pointers would be appreciated!

Thanks.

**Comment by Sibras** [comment]
I havnt actually seen this before but appears there is a bug or some sort of compilation error causing memory corruption.

What version of VS are you using to compile? Also does this error only occur on 32b or 64b builds?

Ill have a look into this first chance I get but in the mean time make sure you have the latest git version for gnutls, nettle and gmp and then try using the Debug builds to see if that gives any further insight.

**Comment by atraczyk** [comment]
Thanks for the quick reply. I'm only compiling 32bit with VS 14.0 (2015) RTM (compiler version 19.00.23506). I've tried both the Debug and the Release builds, with similar results. I will attempt to build with earlier versions of VS. I have VS 11.0 (2012) and VS 12.0 (2013) installed. I'll try both and respond with results. I will also use Page Heap with Gflags to try and isolate the problem.

**Comment by atraczyk** [comment]
Same results with VS 2013 so far.

**Comment by atraczyk** [comment]
Using mpir instead of gmp, and it seems to function properly so far.

**Comment by Sibras** [comment]
OK Sorry for the delay finding the time to fix this. But I was able to reproduce the bug and apply the appropriate fix to the gmp repo.
Try with the updated gmp repo and that should fix the problem.

**Comment by atraczyk** [comment]
Great Job! Thanks!

**Comment by nadendlaprasad** [comment]
Hi, I am facing the same issue while running from VS2017, windows x64. could you please elaborate how you fixed this issue?
