### ISSUE TITLE
Access violation writing location

### ISSUE THREAD

**Issue by nadendlaprasad** [ShiftMediaProject/gnutls#11]
```
	gnutls_global_init();
	gnutls_x509_privkey_t key;
	unsigned int key_length = 4096;
	if (gnutls_x509_privkey_init(&key) != GNUTLS_E_SUCCESS)
		std::cout << "Failed to create private key" << std::endl;
	else
		std::cout << key << std::endl;
	int err = gnutls_x509_privkey_generate(key, GNUTLS_PK_RSA, key_length, 0);
	if (err != GNUTLS_E_SUCCESS) {
		gnutls_x509_privkey_deinit(key);
		std::cout << "Can't generate RSA key pair: " << gnutls_strerror(err) << std::endl;
	}
```

` gnutls_x509_privkey_generate(key, GNUTLS_PK_RSA, key_length, 0);`  this line `throws Access violation writing location`  exception

when i debug into the code , the actual exception is throwing at this line `rsa_generate_keypair(&pub, &priv, NULL, rnd_func, NULL, NULL, level, 0);  ` which is from this file **lib/nettle/pk.c** file

I am running this on VS2017, windows x64

could you please help me out ?

**Comment by Sibras** [comment]
No idea, youll have to debug gnutls_x509_privkey_generate and let me know what you find.
I just pushed a fix that should allow the project to build in debug configuration again which should make it a bit easier to debug.

**Comment by nadendlaprasad** [comment]
I can't get to anywhere while debugging after this line 
file name: **lib/nettle/pk.c**
Error code line:
 ```
rsa_generate_keypair(&pub, &priv, NULL,
						 rnd_func, NULL, NULL,
						 level, 0);

```

It says `source not available ` and oututputs **Access violation writing location message** in the output window. 

I felt like i'm facing same issue as this #1 
and thought this could be the issue with the gmp library and tried building a new library from `gmp` source and linked with the `libgnutls `project but still facing the same issue.

could you please let me know where is the source code of `rsa_generate_keypair` function  so that i can try debug into it ?

**Comment by Sibras** [comment]
rsa_generate_keypair is from the nettle library which gnutls uses as a dependency. If you want to debug into a nettle function then you will need the nettle source code and link your gnutls lib to a debug build of nettle.

The simplest way to do this is to run "project_get_dependencies.bat" from the gnutls SMP folder which will download the source for nettle/gmp/etc. alongside your gnutls folder.

Then you can use the "libgnutls_deps.sln" to open visual studio with the required dependency projects included. Then you can build a debug build that will then also build all required dependencies that are needed.

**Comment by Sibras** [comment]
OK i have located the source of the error. Its due to incorrect assembly calling convention within gmp. Im working on a fix now.

**Comment by Sibras** [comment]
OK a new version of gmp has been uploaded to the repo. If you update your local code and recompile then this should fix the issue. A new set of releases will be added to the release page once the build bot has finished.
