### ISSUE TITLE
in str.h，#include <c-ctype.h>，where can i find this file

### ISSUE THREAD

**Issue by xp19870106** [ShiftMediaProject/gnutls#16]
in str.h，#include <c-ctype.h>，where can i find this file

**Comment by Sibras** [comment]
You need to properly initialise the gnulib submodule.
From the gnutls folder execute 'git submodule update --init'

**Comment by yaoyaoguapi** [comment]
there are nothing in "gunlib",how can I find such XX.c

**Comment by Sibras** [comment]
c-ctype.h is found in the "gnulib\lib\" sub folder. This folder only exists if you initialise submodules as mentioned above

**Comment by xp19870106** [comment]
when compile the files under the gnutls\lib\accelerated\x86 folder,  a lots of error like 
```
#include <nettle/sha.h>
#include <nettle/macros.h>
```
can not find the headers, I have to copy these files from nettle to the gnutls\lib\nettle folder.
Why is that? and am I doing it right?

**Comment by Sibras** [comment]
nettle is a dependency of gnutls you must have already compiled nettle. If you havnt already got nettle then just run the get_dependencies.bat script which will get the required dependencies. Then just open the gnutls_deps.sln which includes all dependencies and will build them for you.

Note: There is a readme in the SMP folder that explains all this.

**Comment by xp19870106** [comment]
Sorry，I‘ve already complied nettle under folder D:\FFMPEG_PROJECT\nettle\SMP by running libnettle_deps， it succeeded. 
And I also have ran the get_dependencies.bat under folder D:\FFMPEG_PROJECT\gnutls\SMP, but I still can not compile libgnutls_deps.sln, the errors are cant't find those files：
```
#include <nettle/sha.h>
#include <nettle/memxor.h>
......
```

**Comment by Sibras** [comment]
Based on your folder structure when compiling nettle it should have created the required headers in D:\msvc\include\nettle.
