### ISSUE TITLE
gnutls_x509_privkey_generate get into infinite loop

### ISSUE THREAD

**Issue by CHUK-ANDREW** [ShiftMediaProject/gnutls#18]
While trying to generate RSA keys application gets into infinite loop. 

1. clone gnutls and execute project_get_dependencies.bat and libgnutls_deps_with_latest_sdk.bat
2. create simple main to generate RSA keys.

Then I run it it get into infinite loop in "__gmpn_gcd_11" function. Adding example into attachments.
[generate_private_key.zip](https://github.com/ShiftMediaProject/gnutls/files/5089978/generate_private_key.zip)

Not sure if this is GnuTLS issue, or Nettle/Hogweed and GMP, as code goes through all of them

* Version Used: GnuTLS master
* Operating System and Version: Windows 10 Home
* Compiler and Version(s): VS2019

**Comment by Sibras** [comment]
It looks like it was a bug in gmp. Ive pushed an update to the gmp repo that should fix the problem.

**Comment by CHUK-ANDREW** [comment]
Thank's a lot! It works great now.
