### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by duiniuluantanqin** [ShiftMediaProject/gnutls#19]
in file `gnutls_int.h`, line 56, 

`#include "attribute.h"` should be `#include "attributes.h"`

**Comment by Sibras** [comment]
Actually "attribute.h" is the correct file which is pulled in from the "gnulib" folder. If you dont have this file then you need to initialise your submodules.

**Comment by duiniuluantanqin** [comment]
sorry, its my negligence,thank you very much.
