### ISSUE TITLE
Cannot clone submodule gnutls/libtasn1

### ISSUE THREAD

**Issue by jcdr428** [ShiftMediaProject/gnutls#20]
The submodule is set to commit 6e8c03bc / version 4.17.0 dated 13 May 2021.

There are illegal characters in libtasn1/tests/invalid-x509 folder files e.g. `:` which prevent copying on Windows.
Therefore the git cloning fails.
 
This has been fixed by commit 76166ddb on 14 May 2021.
The submodule should be set to >commit 76166ddb to allow cloning (e.g. version 4.18.0 dated 09 Nov 21).

**Comment by Sibras** [comment]
This is a known issue. If you look at SMP/project_get_dependencies.bat you'll see the required workaround.

At present the repo tracks the submodule versions from the upstream gnutls repository so they will be updated when the upstream gnutls updates them.

**Comment by Sibras** [comment]
Fixed in 3.8.0 version
