### ISSUE TITLE
Error when attempting to clone ShiftMediaProject/gnutls in VS 2022

### ISSUE THREAD

**Issue by ronchristie52** [ShiftMediaProject/gnutls#24]
I'm trying to clone the project into a fresh install of VS 2022 Community and running into an error as indicated in the error .png attached to this report
The command I'm using is indicated in the git clone dialog .png attached
Also I'm including the last few lines of the log file that's generated in the log .png attached

## Steps to Reproduce

1.  provide the parameters to the clone command as indicated in the git clone dialog .png
2.  click clone
3.  voila!
4.  

## Your Environment

* Version Used:
* Operating System and Version:

Windows 10 Home 22H2
* Compiler and Version(s):
VS 2022 version 17.5.1

## Possible Fix

![VS Git Clone error](https://user-images.githubusercontent.com/7742715/223908735-8d42d507-0e8e-47e6-ae66-fb9b8d016579.PNG)

![VS Git Clone log entries](https://user-images.githubusercontent.com/7742715/223908756-054bb740-a03e-4de2-ab55-44ab2996c5cb.PNG)

![VS Git Clone dialog](https://user-images.githubusercontent.com/7742715/223908708-c77012dc-7f5f-4e99-a61c-ff5e743cf1fc.PNG)

**Comment by Sibras** [comment]
This is a known error with one of the gnutls submodules.
Luckily though they just fixed this and its available in the 3.8.0 release

**Comment by ronchristie52** [comment]
Thanks Matthew! The gnutls project clones successfully. Now I'm trying to figure out how to find and clone the dependencies. I'm new at this stuff, so there's a learning curve. I'll figure it eventually though! ;>

**Comment by Sibras** [comment]
Theres a bat file in the SMP folder for getting dependencies automagically `project_get_dependencies.bat`
