### ISSUE TITLE
libgnutls  #error "Please include config.h first."

### ISSUE THREAD

**Issue by zyw827** [ShiftMediaProject/gnutls#25]
## Context

compile the project libgnutls ,it always error  #error "Please include config.h first."
and  I did import two files in the msvc/include/gl.
## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:win11
* Compiler and Version(s):vs 2022

**Comment by Sibras** [comment]
All the required build files (including config.h) are included in the SMP folder. Only the build files withing that folder are supported by this project and any outside of that should be directed at the upstream gnutls project that this is based on.

**Comment by zyw827** [comment]
Yes ,I  use the SMP, follow your instructions, and I want to compile ffmpeg into static libraries, but why did libgnutls have many errors ,like kinds of Syntax error,and the error I mentioned above. I have no idea about where I might be misconfigured.

**Comment by Sibras** [comment]
So is your actual error when compiling ffmpeg and not with gnutls? You need to provide a proper bug report otherwise theres nothing that can be done to help.

**Comment by zyw827** [comment]
Yes, when compiling ffmpeg, the libgnutls project kept reporting errors, so I commented all about #error  "Please include config.h first." and did something else. Thanks for your reply. I will provide a bug report on Monday.

**Comment by zyw827** [comment]
Well, today I ignore the bug reports and the statistic lib libraries can be used in my project. The errors are listed below.
![image](https://github.com/ShiftMediaProject/gnutls/assets/115475019/11c8b34d-5808-42b6-9093-33ee9f1b420a)

**Comment by zyw827** [comment]
It cannot work correctly.

**Comment by zyw827** [comment]
I solve this problem.

**Comment by 7Yang** [comment]
![image](https://github.com/ShiftMediaProject/gnutls/assets/7731267/4c048740-a3a1-4726-bc05-1a7a041cd38e)
