### ISSUE TITLE
Gnutls *** error: Internal error in memory allocation.

### ISSUE THREAD

**Issue by Sancaros** [ShiftMediaProject/gnutls#30]
## Steps to Reproduce

1.  
2.  
3.  
4.  

## Your Environment

* Version Used:
* Operating System and Version:
* Compiler and Version(s):

**Comment by Sibras** [comment]
Youll need to provide an actual bug report.
Also this project is specific to the visual studio build project files, anything internal to gnutls should be reported to the upstream project.

**Comment by Sibras** [comment]
Closing this due to insufficient information
