### ISSUE TITLE
buffer overrun in _vasprintf()

### ISSUE THREAD

**Issue by ronchristie52** [ShiftMediaProject/gnutls#6]
Hi Matthew,

In your file SMP/stdio.h you've got a function _vasprintf() which calls sprintf() with a va_list as the third argument. I think the call should actually be to vsprintf() instead, otherwise gnutls logging doesn't work and depending on the garbage referenced you can get a buffer overrun since vscprintf() does calculate the space required correctly, but sprintf() can end up using more space than allocated.
Cheers,
Ron

**Comment by Sibras** [comment]
Thanks for the feedback, It looks like the current gnutls head was using an older version of the compat headers. Ive updated the repo to use the latest compat headers so let me know if that fixes your problem.

**Comment by ronchristie52** [comment]
Hi Matthew,
That fixes the issue. Now all I need to do is to figure out where/why my handshake fails. My problem, I'm sure.
Cheers,
Ron
