### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by UMU618** [ShiftMediaProject/gnutls#7]
Compile ReleaseDLL failed

3>nettle_pk.obj : error LNK2019: unresolved external symbol nettle_get_secp_192r1 referenced in function _wrap_nettle_pk_derive
3>nettle_pk.obj : error LNK2019: unresolved external symbol nettle_get_secp_224r1 referenced in function _wrap_nettle_pk_derive
3>nettle_pk.obj : error LNK2019: unresolved external symbol nettle_get_secp_256r1 referenced in function _wrap_nettle_pk_derive
3>nettle_pk.obj : error LNK2019: unresolved external symbol nettle_get_secp_384r1 referenced in function _wrap_nettle_pk_derive
3>nettle_pk.obj : error LNK2019: unresolved external symbol nettle_get_secp_521r1 referenced in function _wrap_nettle_pk_derive

**Comment by Sibras** [comment]
Make sure you use the latest nettle version and this is now fixed.
