### ISSUE TITLE
gnutls vs libgnutls

### ISSUE THREAD

**Issue by nadendlaprasad** [ShiftMediaProject/gnutls#9]
I have downloaded the project and able to build successfully using VS2017. I could able to generate **libgnutls.lib** and **libgnutls.dll** files. 

could you please let me know how can i get **gnutls.lib** and **gnutls.dll** files ? Is **gnutls** a different project? please guide me.

**Comment by Sibras** [comment]
libgnutls.dll is the dll for gnutls. So they are the same thing.

**Comment by nadendlaprasad** [comment]
If you don't mind i have one question please.
why the release version binary includes both  gnutls.liband libgnutls.lib.  How they both are different ?

**Comment by Sibras** [comment]
libgnutls.lib is for linking against a static version of gnutls (i.e. no dll needed) while gnutls.lib is for linking against the dll version. Either one works the same its just a matter of preference as to which one you use.
